[package]
name = "rust-network"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
packet-sniffer = { path = "./packet-sniffer", version = "*" }
byte-slice = { path = "./byte-slice", version = "*" }